### ISSUE TITLE
Seems not work in windows env.

### ISSUE THREAD

**Issue by mboveiri** [ArthurHoaro/web-thumbnailer#24]
Hi.
using `composer require arthurhoaro/web-thumbnailer`
then require by `require_once 'vendor/autoload.php';`
and get `Uncaught Error: Class 'WebThumbnailer' not found in...` 

i see this line in `autoload_namespace.php` : 
```
return array(
    'WebThumbnailer\\' => array($vendorDir . '/arthurhoaro/web-thumbnailer/src', $vendorDir . '/arthurhoaro/web-thumbnailer/tests'),
);
```
seems that is not correct patch.there is a subfolder name `WebThumbnailer`  in this patch nor source files.

**Comment by ArthurHoaro** [comment]
Hi, sorry for the late answer. 

I can not test it on Windows but the autoloading was kind of odd, so I switched to basic PSR-4. That should fix the issue you encountered.
