### ISSUE TITLE
error type given

### ISSUE THREAD

**Issue by agentcobra** [ArthurHoaro/web-thumbnailer#29]
I use  v2.0.3 in shaarli and get this error when refreshing thumbnails:
```
[Thu Nov 05 18:34:21.146472 2020] [php7:notice] [pid 29009] [client 172.17.20.1:38716] TypeError: Argument 1 passed to WebThumbnailer\\Utils\\ImageUtils::isImageString() must be of the type string, bool given, called in /var/www/shaarli.agentcobra.net/vendor/arthurhoaro/web-thumbnailer/src/WebThumbnailer/Finder/DefaultFinder.php on line 59, referer: https://shaarli.agentcobra.net/admin/thumbnails
```
it referer to :
https://github.com/ArthurHoaro/web-thumbnailer/blob/39bfd4f3136d9e6096496b9720e877326cfe4775/src/WebThumbnailer/Finder/DefaultFinder.php#L59
function definition is here : 
https://github.com/ArthurHoaro/web-thumbnailer/blob/39bfd4f3136d9e6096496b9720e877326cfe4775/src/WebThumbnailer/Utils/ImageUtils.php#L177

----

I use:
- Linux
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
- Apache2
```
Server version: Apache/2.4.38 (Debian)
Server built:   2020-08-25T20:08:29
```
- PHP
```
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```
- shaarli
master (commit [48df9f45b8c4b2995c1e04146071628668531b37](https://github.com/shaarli/Shaarli/commit/48df9f45b8c4b2995c1e04146071628668531b37))

**Comment by agentcobra** [comment]
ping @ArthurHoaro

**Comment by ArthurHoaro** [comment]
Sorry for the very late answer. Thanks for the very clear report :+1: 

This can happen if the remote content could not be retrieved. I'll send a PR to fix this and add proper checks before calling this method.
