### ISSUE TITLE
Change quality

### ISSUE THREAD

**Issue by RolandTi** [ArthurHoaro/web-thumbnailer#35]
Hello !
I'm trying to get a better quality for the thumbs.
I changed the line 111 in ImageUtils.php from 
`imagejpeg($targetImg, $target);` to `imagejpeg($targetImg, $target,90);`
but there is still many artifacts. Does I need to add php **imageantialias** or something like this ?
![4747f774d24fd2c6c610fc384b0e3a1c6e2003422501801](https://user-images.githubusercontent.com/28786873/195258588-887e60a9-422f-48c6-8ff6-6d72039bba3d.jpg)

Thanks for your help !

**Comment by RolandTi** [comment]
I think I solved my issue by editing   `imagecopyresized` to `imagecopyresampled` in **ImageUtils.php**

**Comment by nodiscc** [comment]
It would be interesting to see the file size difference between the same thumbnail generated using  `imagecopyresized` and `imagecopyresampled`. It is true that current thumbnails sometimes look quite aliased/ugly.

![image](https://user-images.githubusercontent.com/3950390/195619214-a6ebfdaa-a003-4658-94de-898c5c232879.png)

source: https://www.youtube.com/watch?v=HsZUAq5yvw4

![image](https://user-images.githubusercontent.com/3950390/195619689-d33104a8-071f-42e0-ae6e-a8c0249c5591.png)

source: https://www.wolframalpha.com/

If the size difference is not very important, maybe it could be switched to `imagecopyresampled`? Or made configurable?

**Comment by RolandTi** [comment]
![23e08f1a446d1fcb2840759503cffab06460788f2501801](https://user-images.githubusercontent.com/28786873/195634626-ec80e2ac-43f1-4f00-a507-8ba30dc5dda7.jpg)
![23e08f1a446d1fcb2840759503cffab06460788f2501801-1](https://user-images.githubusercontent.com/28786873/195634635-87f84476-e923-461c-accf-d3e5988e33a5.jpg)

11ko and 12ko (using 80% quality for jpeg instead of default 75%)

I need to look a little bit more, because I got some "error 500" while generating from scratch all thumbs. Maybe `imagecopyresampled` ask to much ressources.

**Comment by ArthurHoaro** [comment]
Thanks for the suggestion, it does look way nicer! I have added this change under a setting that is now enabled by default.
